apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerce-service-pod
  template:
    metadata:
      labels:
        app: commerce-service-pod
    spec:
      serviceAccountName: commerce-service-account
      containers:
      - name: commerce-service-container
        image: gcr.io/phading-dev/commerce-service:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "400m"
            memory: "512Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: commerce-service-monitoring
spec:
  selector:
    matchLabels:
      app: commerce-service-pod
  endpoints:
  - port: 8080
    path: /metricsz
    interval: 30s
---
apiVersion: v1
kind: Service
metadata:
  name: commerce-service
spec:
  selector:
    app: commerce-service-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: commerce-service-lb-health-check
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 80
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: commerce-service
