apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commerce-service-pod
  template:
    metadata:
      labels:
        app: commerce-service-pod
    spec:
      serviceAccountName: commerce-service-account
      containers:
      - name: commerce-service-container
        image: gcr.io/phading-prod/commerce-service:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: commerce-service-monitoring
spec:
  selector:
    matchLabels:
      app: commerce-service-pod
  endpoints:
  - port: 8080
    path: /metricsz
    interval: 30s
---
apiVersion: v1
kind: Service
metadata:
  name: commerce-service
spec:
  selector:
    app: commerce-service-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: commerce-service-lb-health-check
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: commerce-service
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: commerce-service-route-internal
spec:
  parentRefs:
  - name: phading-gateway-internal
    sectionName: http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /cn
    backendRefs:
    - name: commerce-service
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: commerce-service-route-external
spec:
  parentRefs:
  - name: phading-gateway-external
    sectionName: https
  hostnames:
  - www.secount.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /cw
    backendRefs:
    - name: commerce-service
      port: 8080
