- kind: Enum
  name: PaymentProfileState
  values:
    - name: HEALTHY
      value: 1
    - name: SUSPENDED
      value: 2
- kind: Message
  name: PaymentProfileStateInfo
  fields:
    - name: version
      type: number
      index: 1
    - name: state
      type: PaymentProfileState
      index: 2
    - name: updatedTimeMs
      type: number
      index: 3
- kind: Enum
  name: StripeConnectedAccountState
  values:
    - name: ONBOARDING
      value: 1
    - name: ONBOARDED
      value: 2
- kind: Message
  name: LineItem
  fields:
    - name: productID
      type: ProductID
      import: "@phading/price/price"
      index: 1
    - name: unit # The unit for the quantity.
      type: string
      index: 2
    - name: amountType
      type: AmountType
      import: "@phading/price/amount_type"
      index: 3
    - name: quantity # The number of units per price config.
      type: number
      index: 4
    - name: amount # Amount under the smallest unit of the currency. E.g. cents for USD.
      type: number
      index: 5
- kind: Message
  name: TransactionStatement
  fields:
    - name: currency
      type: string
      index: 1
    - name: totalAmount # Amount under the smallest unit of the currency. E.g. cents for USD.
      type: number
      index: 2
    - name: totalAmountType
      type: AmountType
      import: "@phading/price/amount_type"
      index: 3
    - name: items
      type: LineItem
      isArray: true
      index: 4
- kind: Enum
  name: PaymentState
  values:
    - name: PROCESSING
      value: 1
    - name: CHARGING_VIA_STRIPE_INVOICE
      value: 2
    - name: PAID
      value: 3
    - name: FAILED
      value: 4
- kind: Enum
  name: PayoutState
  values:
    - name: PROCESSING
      value: 1
    - name: PAID
      value: 2
    - name: DISABLED
      value: 3
- kind: SpannerDatabase
  name: CommerceDatabase
  tables:
    - kind: Table
      name: PaymentProfile
      columns:
        - name: accountId
          type: string
        - name: stripePaymentCustomerId
          type: string
          nullable: true
        - name: stateInfo
          type: PaymentProfileStateInfo
          nullable: true
        - name: firstPaymentTimeMs
          type: float64
          nullable: true
        - name: createdTimeMs
          type: float64
          nullable: true
      primaryKeys:
        - accountId
      insert: InsertPaymentProfile
      delete: DeletePaymentProfile
      get: GetPaymentProfile
    - kind: Table
      name: PayoutProfile
      columns:
        - name: accountId
          type: string
        - name: stripeConnectedAccountId
          type: string
          nullable: true
        - name: stripeConnectedAccountState
          type: StripeConnectedAccountState
          nullable: true
        - name: createdTimeMs
          type: float64
          nullable: true
      primaryKeys:
        - accountId
      insert: InsertPayoutProfile
      delete: DeletePayoutProfile
      get: GetPayoutProfile
    - kind: Table
      name: TransactionStatement
      columns:
        - name: statementId
          type: string
        - name: accountId
          type: string
          nullable: true
        - name: month
          type: string
          nullable: true
        - name: statement
          type: TransactionStatement
          nullable: true
        - name: createdTimeMs
          type: float64
          nullable: true
      primaryKeys:
        - statementId
      indexes:
        - name: StatementByMonth
          columns:
            - accountId
            - statementId
            - name: month
              desc: true
      insert: InsertTransactionStatement
      delete: DeleteTransactionStatement
      get: GetTransactionStatement
    - kind: Table
      name: Payment
      columns:
        - name: statementId
          type: string
        - name: accountId
          type: string
          nullable: true
        - name: state
          type: PaymentState
          nullable: true
        - name: stripeInvoiceId
          type: string
          nullable: true
        - name: updatedTimeMs
          type: float64
          nullable: true
        - name: createdTimeMs
          type: float64
          nullable: true
      primaryKeys:
        - statementId
      indexes:
        - name: PaymentByState
          columns:
            - accountId
            - state
            - name: createdTimeMs
              desc: true
      insert: InsertPayment
      delete: DeletePayment
      get: GetPayment
    - kind: Table
      name: Payout
      columns:
        - name: statementId
          type: string
        - name: accountId
          type: string
          nullable: true
        - name: state
          type: PayoutState
          nullable: true
        - name: stripeTransferId
          type: string
          nullable: true
        - name: updatedTimeMs
          type: float64
          nullable: true
        - name: createdTimeMs
          type: float64
          nullable: true
      primaryKeys:
        - statementId
      indexes:
        - name: PayoutByState
          columns:
            - accountId
            - state
            - name: createdTimeMs
              desc: true
      insert: InsertPayout
      delete: DeletePayout
      get: GetPayout
    - kind: TaskTable
      name: StripePaymentCustomerCreatingTask
      columns:
        - name: accountId
          type: string
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - accountId
      executionTimeIndex: StripePaymentCustomerCreatingTaskByExecutionTime
      insert: InsertStripePaymentCustomerCreatingTask
      delete: DeleteStripePaymentCustomerCreatingTask
      get: GetStripePaymentCustomerCreatingTask
      listPendingTasks: ListPendingStripePaymentCustomerCreatingTasks
      getMetadata: GetStripePaymentCustomerCreatingTaskMetadata
      updateMetadata: UpdateStripePaymentCustomerCreatingTaskMetadata
    - kind: TaskTable
      name: StripeConnectedAccountCreatingTask
      columns:
        - name: accountId
          type: string
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - accountId
      executionTimeIndex: StripeConnectedAccountCreatingTaskByExecutionTime
      insert: InsertStripeConnectedAccountCreatingTask
      delete: DeleteStripeConnectedAccountCreatingTask
      get: GetStripeConnectedAccountCreatingTask
      listPendingTasks: ListPendingStripeConnectedAccountCreatingTasks
      getMetadata: GetStripeConnectedAccountCreatingTaskMetadata
      updateMetadata: UpdateStripeConnectedAccountCreatingTaskMetadata
    - kind: TaskTable
      name: StripeConnectedAccountNeedsSetupNotifyingTask
      columns:
        - name: accountId
          type: string
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - accountId
      executionTimeIndex: StripeConnectedAccountNeedsSetupNotifyingTaskByExecutionTime
      insert: InsertStripeConnectedAccountNeedsSetupNotifyingTask
      delete: DeleteStripeConnectedAccountNeedsSetupNotifyingTask
      get: GetStripeConnectedAccountNeedsSetupNotifyingTask
      listPendingTasks: ListPendingStripeConnectedAccountNeedsSetupNotifyingTasks
      getMetadata: GetStripeConnectedAccountNeedsSetupNotifyingTaskMetadata
      updateMetadata: UpdateStripeConnectedAccountNeedsSetupNotifyingTaskMetadata
    - kind: TaskTable
      name: PaymentTask
      columns:
        - name: statementId
          type: string
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - statementId
      executionTimeIndex: PaymentTaskByExecutionTime
      insert: InsertPaymentTask
      delete: DeletePaymentTask
      get: GetPaymentTask
      listPendingTasks: ListPendingPaymentTasks
      getMetadata: GetPaymentTaskMetadata
      updateMetadata: UpdatePaymentTaskMetadata
    - kind: TaskTable
      name: PaymentMethodNeedsUpdateNotifyingTask
      columns:
        - name: statementId
          type: string
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - statementId
      executionTimeIndex: PaymentMethodNeedsUpdateNotifyingTaskByExecutionTime
      insert: InsertPaymentMethodNeedsUpdateNotifyingTask
      delete: DeletePaymentMethodNeedsUpdateNotifyingTask
      get: GetPaymentMethodNeedsUpdateNotifyingTask
      listPendingTasks: ListPendingPaymentMethodNeedsUpdateNotifyingTasks
      getMetadata: GetPaymentMethodNeedsUpdateNotifyingTaskMetadata
      updateMetadata: UpdatePaymentMethodNeedsUpdateNotifyingTaskMetadata
    - kind: TaskTable
      name: PaymentProfileSuspendingDueToPastDueTask
      columns:
        - name: statementId
          type: string
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - statementId
      executionTimeIndex: PaymentProfileSuspendingDueToPastDueTaskByExecutionTime
      insert: InsertPaymentProfileSuspendingDueToPastDueTask
      delete: DeletePaymentProfileSuspendingDueToPastDueTask
      get: GetPaymentProfileSuspendingDueToPastDueTask
      listPendingTasks: ListPendingPaymentProfileSuspendingDueToPastDueTasks
      getMetadata: GetPaymentProfileSuspendingDueToPastDueTaskMetadata
      updateMetadata: UpdatePaymentProfileSuspendingDueToPastDueTaskMetadata
    - kind: TaskTable
      name: PaymentProfileSuspensionNotifyingTask
      columns:
        - name: accountId
          type: string
        - name: version
          type: float64
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - accountId
        - version
      executionTimeIndex: PaymentProfileSuspensionNotifyingTaskByExecutionTime
      insert: InsertPaymentProfileSuspensionNotifyingTask
      delete: DeletePaymentProfileSuspensionNotifyingTask
      get: GetPaymentProfileSuspensionNotifyingTask
      listPendingTasks: ListPendingPaymentProfileSuspensionNotifyingTasks
      getMetadata: GetPaymentProfileSuspensionNotifyingTaskMetadata
      updateMetadata: UpdatePaymentProfileSuspensionNotifyingTaskMetadata
    - kind: TaskTable
      name: PaymentProfileStateSyncingTask
      columns:
        - name: accountId
          type: string
        - name: version
          type: float64
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - accountId
        - version
      executionTimeIndex: PaymentProfileStateSyncingTaskByExecutionTime
      insert: InsertPaymentProfileStateSyncingTask
      delete: DeletePaymentProfileStateSyncingTask
      get: GetPaymentProfileStateSyncingTask
      listPendingTasks: ListPendingPaymentProfileStateSyncingTasks
      getMetadata: GetPaymentProfileStateSyncingTaskMetadata
      updateMetadata: UpdatePaymentProfileStateSyncingTaskMetadata
    - kind: TaskTable
      name: PayoutTask
      columns:
        - name: statementId
          type: string
      retryCountColumn: retryCount
      executionTimeColumn: executionTimeMs
      createdTimeColumn: createdTimeMs
      primaryKeys:
        - statementId
      executionTimeIndex: PayoutTaskByExecutionTime
      insert: InsertPayoutTask
      delete: DeletePayoutTask
      get: GetPayoutTask
      listPendingTasks: ListPendingPayoutTasks
      getMetadata: GetPayoutTaskMetadata
      updateMetadata: UpdatePayoutTaskMetadata
  updates:
    - name: UpdatePaymentProfileState
      table: PaymentProfile
      where:
        op: AND
        exprs:
          - op: =
            lColumn: accountId
      set:
        - stateInfo
    - name: UpdatePaymentProfilePaymentCustomer
      table: PaymentProfile
      where:
        op: AND
        exprs:
          - op: =
            lColumn: accountId
      set:
        - stripePaymentCustomerId
    - name: UpdatePayoutProfileConnectedAccount
      table: PayoutProfile
      where:
        op: AND
        exprs:
          - op: =
            lColumn: accountId
      set:
        - stripeConnectedAccountId
        - stripeConnectedAccountState
    - name: UpdatePayoutProfileConnectedAccountState
      table: PayoutProfile
      where:
        op: AND
        exprs:
          - op: =
            lColumn: accountId
      set:
        - stripeConnectedAccountState
    - name: UpdatePaymentState
      table: Payment
      where:
        op: AND
        exprs:
          - op: =
            lColumn: statementId
      set:
        - state
        - updatedTimeMs
    - name: UpdatePaymentStateAndStripeInvoice
      table: Payment
      where:
        op: AND
        exprs:
          - op: =
            lColumn: statementId
      set:
        - state
        - stripeInvoiceId
        - updatedTimeMs
    - name: UpdatePayoutState
      table: Payout
      where:
        op: AND
        exprs:
          - op: =
            lColumn: statementId
      set:
        - state
        - updatedTimeMs
    - name: UpdatePayoutStateAndStripeTransfer
      table: Payout
      where:
        op: AND
        exprs:
          - op: =
            lColumn: statementId
      set:
        - state
        - stripeTransferId
        - updatedTimeMs
  selects:
    - name: GetPaymentProfileFromStatement
      from: TransactionStatement
      as: t
      join:
        - type: INNER
          with: PaymentProfile
          as: b
          on:
            op: =
            lColumn: accountId
            lTable: t
            rColumn: accountId
      where:
        op: AND
        exprs:
          - op: =
            lColumn: statementId
      get:
        - all: true
          table: b
    - name: GetPayoutProfileFromStatement
      from: TransactionStatement
      as: t
      join:
        - type: INNER
          with: PayoutProfile
          as: e
          on:
            op: =
            lColumn: accountId
            lTable: t
            rColumn: accountId
      where:
        op: AND
        exprs:
          - op: =
            lColumn: statementId
      get:
        - all: true
          table: e
    - name: GetTransactionStatementByMonth
      from: TransactionStatement
      where:
        op: AND
        exprs:
          - op: =
            lColumn: accountId
          - op: =
            lColumn: month
      get:
        - all: true
    - name: ListTransactionStatements
      from: TransactionStatement
      where:
        op: AND
        exprs:
          - op: =
            lColumn: accountId
          - op: ">="
            lColumn: month
          - op: "<="
            lColumn: month
      orderBy:
        - column: month
          desc: true
      get:
        - all: true
    - name: ListPaymentsByState
      from: Payment
      where:
        op: AND
        exprs:
          - op: =
            lColumn: accountId
          - op: =
            lColumn: state
      orderBy:
        - column: createdTimeMs
          desc: true
      get:
        - all: true
    - name: ListPaymentsWithStatements
      from: Payment
      as: p
      join:
        - type: LEFT
          with: TransactionStatement
          as: t
          on:
            op: =
            lColumn: statementId
            lTable: p
            rColumn: statementId
      where:
        op: AND
        exprs:
          - op: =
            lColumn: accountId
            lTable: p
          - op: ">="
            lColumn: month
            lTable: t
          - op: "<="
            lColumn: month
            lTable: t
      orderBy:
        - column: month
          table: t
          desc: true
      get:
        - all: true
          table: p
        - all: true
          table: t
    - name: ListPayoutsByState
      from: Payout
      where:
        op: AND
        exprs:
          - op: =
            lColumn: accountId
          - op: =
            lColumn: state
      orderBy:
        - column: createdTimeMs
          desc: true
      get:
        - all: true
    - name: ListPayoutsWithStatements
      from: Payout
      as: p
      join:
        - type: LEFT
          with: TransactionStatement
          as: t
          on:
            op: =
            lColumn: statementId
            lTable: p
            rColumn: statementId
      where:
        op: AND
        exprs:
          - op: =
            lColumn: accountId
            lTable: p
          - op: ">="
            lColumn: month
            lTable: t
          - op: "<="
            lColumn: month
            lTable: t
      orderBy:
        - column: month
          table: t
          desc: true
      get:
        - all: true
          table: p
        - all: true
          table: t
  outputDdl: ./db/ddl
  outputSql: ./db/sql
