export let GRACE_PERIOD_DAYS = 10;
export let GRACE_PERIOD_DAYS_IN_MS = GRACE_PERIOD_DAYS * 24 * 60 * 60 * 1000;
export let PLATFORM_NAME="Secount";
export let SUPPORT_EMAIL_NAME="Secount Support";
export let MERCHANT_CATEGORY_CODE="5815"; 
export let PRODUCT_DESCRIPTION = "Digital goods";
export let PAYMENT_METADATA_STATEMENT_ID_KEY = "statementId";
export let CUSTOMER_METADATA_ACCOUNT_ID_KEY = "accountId";
export let CONNECTED_ACCOUNT_METADATA_ACCOUNT_ID_KEY = "accountId";
